In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.4'

## Create & Read

1D Array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(6,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

6

2D Array

In [10]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [11]:
arr2.ndim

2

In [12]:
arr2. # (row, col)

SyntaxError: invalid syntax (1022218778.py, line 1)

In [ ]:
arr2.size

In [ ]:
arr2.dtype

In [ ]:
type(arr2)

3D Array

In [14]:
arr3 = np.array([[[1, 4, 5],[6, 5, 4], [6, 7, 4]], [[3, 5, 4],[6, 5, 4],[5, 8, 7]], [[1, 4, 5],[6, 5, 4], [6, 7, 4]]])
arr3

array([[[1, 4, 5],
        [6, 5, 4],
        [6, 7, 4]],

       [[3, 5, 4],
        [6, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 5, 4],
        [6, 7, 4]]])

In [ ]:
arr3.ndim

In [ ]:
arr3.shape

In [ ]:
arr3.size

Create random array

In [ ]:
randomArr = np.random.rand(3, 2, 3)
randomArr

In [ ]:
randomArr.dtype

In [57]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
full = np.full((3, 2, 3), 9)
full

In [ ]:
ones = np.ones((3, 2, 3))
ones

In [ ]:
arr3

In [ ]:
arr3[0]

In [ ]:
arr3[0][0][1]

In [ ]:
arr3[0:2]

In [ ]:
arr3[1][0][0]

In [15]:
arr3

array([[[1, 4, 5],
        [6, 5, 4],
        [6, 7, 4]],

       [[3, 5, 4],
        [6, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 5, 4],
        [6, 7, 4]]])

In [16]:
arr3[-1]

array([[1, 4, 5],
       [6, 5, 4],
       [6, 7, 4]])

In [17]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [18]:
a1

array([[[0.4986336 , 0.84558645],
        [0.65918092, 0.4090918 ],
        [0.38748751, 0.9570063 ]],

       [[0.28152433, 0.28945513],
        [0.03040849, 0.16683473],
        [0.68144752, 0.27728137]]])

In [19]:
a2

array([[[0.80228863, 0.9445045 ],
        [0.0446097 , 0.53495606],
        [0.68597096, 0.27678323]],

       [[0.70427887, 0.85084015],
        [0.21218033, 0.21589425],
        [0.08520824, 0.70387984]]])

In [20]:
np.add(a1, a2)

array([[[1.30092223, 1.79009094],
        [0.70379062, 0.94404787],
        [1.07345847, 1.23378953]],

       [[0.9858032 , 1.14029528],
        [0.24258882, 0.38272898],
        [0.76665577, 0.9811612 ]]])

In [21]:
np.subtract(a1, a2)

array([[[-0.30365502, -0.09891805],
        [ 0.61457121, -0.12586426],
        [-0.29848345,  0.68022307]],

       [[-0.42275454, -0.56138501],
        [-0.18177184, -0.04905951],
        [ 0.59623928, -0.42659847]]])

In [22]:
np.divide(a1, a2)

array([[[ 0.62151399,  0.8952699 ],
        [14.776626  ,  0.76472038],
        [ 0.56487451,  3.45760224]],

       [[ 0.39973417,  0.3401992 ],
        [ 0.14331436,  0.77276137],
        [ 7.99743673,  0.39393281]]])

In [23]:
np.multiply(a1, a2)

array([[[0.40004807, 0.7986602 ],
        [0.02940587, 0.21884614],
        [0.26580518, 0.26488329]],

       [[0.19827164, 0.24628005],
        [0.00645208, 0.03601866],
        [0.05806495, 0.19517276]]])

Stastical operations

In [29]:
sqrt = np.sqrt(25)
abs1 = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [30]:
sqrt

np.float64(5.0)

In [34]:
power

np.int64(256)

In [35]:
log

np.float64(3.2188758248682006)

In [36]:
mins

np.float64(0.030408487968980547)

In [37]:
maxs

np.float64(0.9445044958543278)

 Update

In [38]:
arr3

array([[[1, 4, 5],
        [6, 5, 4],
        [6, 7, 4]],

       [[3, 5, 4],
        [6, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 5, 4],
        [6, 7, 4]]])

In [39]:
arr3[0, 0, 2] = 500

In [40]:
arr3

array([[[  1,   4, 500],
        [  6,   5,   4],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  6,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   5,   4],
        [  6,   7,   4]]])

In [42]:
arr3.sort()

In [43]:
arr3

array([[[  1,   4, 500],
        [  4,   5,   6],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  4,   5,   6],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   5,   6],
        [  4,   6,   7]]])

# Reshape

In [53]:
arr3.shape

(3, 3, 3)

In [54]:
arr3_reshape = arr3.reshape(3, 3, -1)
arr3_reshape

array([[[  1,   4, 500],
        [  4,   5,   6],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  4,   5,   6],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   5,   6],
        [  4,   6,   7]]])

#### Appending & Inserting

Appending

zeroes

In [61]:
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
appd = np.append(zeroes, new_array, axis =0)

In [63]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Inseting

In [66]:
inserted_array = np.insert(zeroes, 1, new_array, axis =0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

Delete

In [68]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.44937582, 0.32800073, 0.84422308],
        [0.10966543, 0.33748166, 0.8138982 ]],

       [[0.48845293, 0.13155196, 0.814825  ],
        [0.41474243, 0.27122446, 0.31698244]],

       [[0.54639065, 0.25632369, 0.0973381 ],
        [0.32166451, 0.67976042, 0.18538439]]])

In [76]:
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.10966543, 0.33748166, 0.8138982 ]],

       [[0.41474243, 0.27122446, 0.31698244]],

       [[0.32166451, 0.67976042, 0.18538439]]])

In [77]:
np.save("new_array", arr5)

In [80]:
arr6 = np.load("new_array.npy")
arr6

array([[[0.10966543, 0.33748166, 0.8138982 ]],

       [[0.41474243, 0.27122446, 0.31698244]],

       [[0.32166451, 0.67976042, 0.18538439]]])